// <auto-generated />
using System;
using Herencia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Herencia.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260710230656_Agregar2FAyArchivosActivos")]
    partial class Agregar2FAyArchivosActivos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Herencia.Data.Models.ActivoDigital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreArchivoOriginal")
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaArchivo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ActivosDigitales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Caja de ahorro en pesos",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cuenta Banco Santander",
                            Tipo = 0,
                            UsuarioCreacion = "seed",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Cuenta corriente en dolares",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cuenta Banco Galicia",
                            Tipo = 0,
                            UsuarioCreacion = "seed",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Perfil publico con 5000 seguidores",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Instagram personal",
                            Tipo = 1,
                            UsuarioCreacion = "seed",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Perfil familiar",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Facebook personal",
                            Tipo = 1,
                            UsuarioCreacion = "seed",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Wallet Ethereum",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Billetera MetaMask",
                            Tipo = 2,
                            UsuarioCreacion = "seed",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Exchange con balance en USDT",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Billetera Binance",
                            Tipo = 2,
                            UsuarioCreacion = "seed",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Cuenta de correo con backups de fotos",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Correo Gmail principal",
                            Tipo = 3,
                            UsuarioCreacion = "seed",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Cuenta de correo del trabajo anterior",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Correo Outlook laboral",
                            Tipo = 3,
                            UsuarioCreacion = "seed",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Dominio registrado en un proveedor DNS",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Dominio web personal",
                            Tipo = 4,
                            UsuarioCreacion = "seed",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Caja de ahorro en pesos",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cuenta Banco Nacion",
                            Tipo = 0,
                            UsuarioCreacion = "seed",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 11,
                            Descripcion = "Plazo fijo renovable",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cuenta Banco BBVA",
                            Tipo = 0,
                            UsuarioCreacion = "seed",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 12,
                            Descripcion = "Perfil profesional con recomendaciones",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "LinkedIn profesional",
                            Tipo = 1,
                            UsuarioCreacion = "seed",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 13,
                            Descripcion = "Hardware wallet con Bitcoin",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Billetera Ledger",
                            Tipo = 2,
                            UsuarioCreacion = "seed",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 14,
                            Descripcion = "Cuenta de respaldo",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Correo Gmail secundario",
                            Tipo = 3,
                            UsuarioCreacion = "seed",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 15,
                            Descripcion = "Suscripcion de streaming compartida",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cuenta Netflix",
                            Tipo = 4,
                            UsuarioCreacion = "seed",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 16,
                            Descripcion = "Caja de ahorro en pesos",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cuenta Banco Macro",
                            Tipo = 0,
                            UsuarioCreacion = "seed",
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 17,
                            Descripcion = "Perfil personal",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cuenta X (Twitter)",
                            Tipo = 1,
                            UsuarioCreacion = "seed",
                            UsuarioId = 3
                        });
                });

            modelBuilder.Entity("Herencia.Data.Models.AsignacionHerencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivoDigitalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CondicionLiberacion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailInvitado")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaLiberacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcentajeAsignado")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenInvitacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivoDigitalId");

                    b.HasIndex("TokenInvitacion")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("AsignacionesHerencia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivoDigitalId = 1,
                            CondicionLiberacion = "Certificado de defuncion + 30 dias",
                            EmailInvitado = "ana.torres@example.com",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PorcentajeAsignado = 50.00m,
                            TokenInvitacion = "seed-token-0000000000000000000000000000001",
                            UsuarioCreacion = "seed",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 2,
                            ActivoDigitalId = 1,
                            CondicionLiberacion = "Certificado de defuncion + 30 dias",
                            EmailInvitado = "carlos.sosa@example.com",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PorcentajeAsignado = 50.00m,
                            TokenInvitacion = "seed-token-0000000000000000000000000000002",
                            UsuarioCreacion = "seed",
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 3,
                            ActivoDigitalId = 10,
                            CondicionLiberacion = "Certificado de defuncion",
                            EmailInvitado = "carlos.sosa@example.com",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PorcentajeAsignado = 100.00m,
                            TokenInvitacion = "seed-token-0000000000000000000000000000003",
                            UsuarioCreacion = "seed",
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            ActivoDigitalId = 5,
                            CondicionLiberacion = "Certificado de defuncion",
                            EmailInvitado = "invitado.sinregistro@example.com",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PorcentajeAsignado = 100.00m,
                            TokenInvitacion = "seed-token-0000000000000000000000000000004",
                            UsuarioCreacion = "seed"
                        },
                        new
                        {
                            Id = 5,
                            ActivoDigitalId = 13,
                            CondicionLiberacion = "Mayoria de edad del beneficiario",
                            EmailInvitado = "maximiceli@hotmail.com.ar",
                            Estado = 2,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PorcentajeAsignado = 100.00m,
                            TokenInvitacion = "seed-token-0000000000000000000000000000005",
                            UsuarioCreacion = "seed",
                            UsuarioId = 1
                        });
                });

            modelBuilder.Entity("Herencia.Data.Models.CertificadoDefuncion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreArchivoOriginal")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RevisadoPorUsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("SubidoPorUsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioTitularId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RevisadoPorUsuarioId");

                    b.HasIndex("SubidoPorUsuarioId");

                    b.HasIndex("UsuarioTitularId");

                    b.ToTable("CertificadosDefuncion");
                });

            modelBuilder.Entity("Herencia.Data.Models.ConfiguracionVerificacionVida", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContactoConfianzaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaProtocoloActivado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaUltimoRecordatorio")
                        .HasColumnType("TEXT");

                    b.Property<int>("FrecuenciaMeses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Metodo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordatoriosEnviados")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UltimoCheckIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.HasIndex("ContactoConfianzaId");

                    b.ToTable("ConfiguracionesVerificacionVida");
                });

            modelBuilder.Entity("Herencia.Data.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoDobleFactor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CodigoDobleFactorExpiracion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DobleFactorHabilitado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("PasswordResetExpiracion")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DobleFactorHabilitado = false,
                            Email = "maximiceli@hotmail.com.ar",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Maximiliano Miceli",
                            PasswordHash = new byte[] { 238, 80, 212, 122, 120, 99, 196, 28, 15, 95, 240, 202, 142, 160, 229, 144, 222, 15, 32, 162, 252, 201, 219, 4, 183, 118, 147, 154, 18, 19, 2, 128, 87, 161, 210, 116, 193, 216, 155, 50, 203, 120, 193, 246, 150, 150, 34, 133, 232, 39, 150, 231, 92, 172, 241, 162, 55, 180, 25, 184, 11, 135, 145, 187 },
                            PasswordSalt = new byte[] { 28, 118, 17, 175, 2, 68, 207, 43, 21, 146, 52, 91, 125, 60, 48, 185, 142, 182, 240, 38, 14, 66, 255, 71, 129, 181, 161, 231, 13, 227, 58, 95, 88, 70, 195, 191, 246, 92, 245, 183, 166, 190, 116, 241, 69, 123, 74, 14, 227, 191, 76, 118, 217, 248, 40, 243, 88, 165, 159, 205, 226, 22, 163, 29, 212, 222, 135, 0, 111, 91, 238, 169, 89, 30, 46, 86, 107, 2, 225, 226, 123, 24, 31, 243, 129, 96, 56, 86, 120, 24, 41, 203, 167, 194, 119, 223, 37, 169, 69, 233, 95, 105, 11, 98, 51, 18, 20, 30, 137, 75, 214, 95, 38, 224, 14, 204, 244, 35, 20, 136, 3, 19, 58, 229, 81, 74, 169, 53 },
                            Rol = 1,
                            UsuarioCreacion = "seed"
                        },
                        new
                        {
                            Id = 2,
                            DobleFactorHabilitado = false,
                            Email = "ana.torres@example.com",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Ana Torres",
                            PasswordHash = new byte[] { 238, 80, 212, 122, 120, 99, 196, 28, 15, 95, 240, 202, 142, 160, 229, 144, 222, 15, 32, 162, 252, 201, 219, 4, 183, 118, 147, 154, 18, 19, 2, 128, 87, 161, 210, 116, 193, 216, 155, 50, 203, 120, 193, 246, 150, 150, 34, 133, 232, 39, 150, 231, 92, 172, 241, 162, 55, 180, 25, 184, 11, 135, 145, 187 },
                            PasswordSalt = new byte[] { 28, 118, 17, 175, 2, 68, 207, 43, 21, 146, 52, 91, 125, 60, 48, 185, 142, 182, 240, 38, 14, 66, 255, 71, 129, 181, 161, 231, 13, 227, 58, 95, 88, 70, 195, 191, 246, 92, 245, 183, 166, 190, 116, 241, 69, 123, 74, 14, 227, 191, 76, 118, 217, 248, 40, 243, 88, 165, 159, 205, 226, 22, 163, 29, 212, 222, 135, 0, 111, 91, 238, 169, 89, 30, 46, 86, 107, 2, 225, 226, 123, 24, 31, 243, 129, 96, 56, 86, 120, 24, 41, 203, 167, 194, 119, 223, 37, 169, 69, 233, 95, 105, 11, 98, 51, 18, 20, 30, 137, 75, 214, 95, 38, 224, 14, 204, 244, 35, 20, 136, 3, 19, 58, 229, 81, 74, 169, 53 },
                            Rol = 0,
                            UsuarioCreacion = "seed"
                        },
                        new
                        {
                            Id = 3,
                            DobleFactorHabilitado = false,
                            Email = "carlos.sosa@example.com",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Carlos Sosa",
                            PasswordHash = new byte[] { 238, 80, 212, 122, 120, 99, 196, 28, 15, 95, 240, 202, 142, 160, 229, 144, 222, 15, 32, 162, 252, 201, 219, 4, 183, 118, 147, 154, 18, 19, 2, 128, 87, 161, 210, 116, 193, 216, 155, 50, 203, 120, 193, 246, 150, 150, 34, 133, 232, 39, 150, 231, 92, 172, 241, 162, 55, 180, 25, 184, 11, 135, 145, 187 },
                            PasswordSalt = new byte[] { 28, 118, 17, 175, 2, 68, 207, 43, 21, 146, 52, 91, 125, 60, 48, 185, 142, 182, 240, 38, 14, 66, 255, 71, 129, 181, 161, 231, 13, 227, 58, 95, 88, 70, 195, 191, 246, 92, 245, 183, 166, 190, 116, 241, 69, 123, 74, 14, 227, 191, 76, 118, 217, 248, 40, 243, 88, 165, 159, 205, 226, 22, 163, 29, 212, 222, 135, 0, 111, 91, 238, 169, 89, 30, 46, 86, 107, 2, 225, 226, 123, 24, 31, 243, 129, 96, 56, 86, 120, 24, 41, 203, 167, 194, 119, 223, 37, 169, 69, 233, 95, 105, 11, 98, 51, 18, 20, 30, 137, 75, 214, 95, 38, 224, 14, 204, 244, 35, 20, 136, 3, 19, 58, 229, 81, 74, 169, 53 },
                            Rol = 0,
                            UsuarioCreacion = "seed"
                        });
                });

            modelBuilder.Entity("Herencia.Data.Models.ActivoDigital", b =>
                {
                    b.HasOne("Herencia.Data.Models.Usuario", "Usuario")
                        .WithMany("ActivosOtorgados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Herencia.Data.Models.AsignacionHerencia", b =>
                {
                    b.HasOne("Herencia.Data.Models.ActivoDigital", "ActivoDigital")
                        .WithMany("AsignacionesHerencia")
                        .HasForeignKey("ActivoDigitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Herencia.Data.Models.Usuario", "Usuario")
                        .WithMany("HerenciasRecibidas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActivoDigital");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Herencia.Data.Models.CertificadoDefuncion", b =>
                {
                    b.HasOne("Herencia.Data.Models.Usuario", "RevisadoPor")
                        .WithMany()
                        .HasForeignKey("RevisadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Herencia.Data.Models.Usuario", "SubidoPor")
                        .WithMany()
                        .HasForeignKey("SubidoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Herencia.Data.Models.Usuario", "UsuarioTitular")
                        .WithMany()
                        .HasForeignKey("UsuarioTitularId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RevisadoPor");

                    b.Navigation("SubidoPor");

                    b.Navigation("UsuarioTitular");
                });

            modelBuilder.Entity("Herencia.Data.Models.ConfiguracionVerificacionVida", b =>
                {
                    b.HasOne("Herencia.Data.Models.Usuario", "ContactoConfianza")
                        .WithMany()
                        .HasForeignKey("ContactoConfianzaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Herencia.Data.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("Herencia.Data.Models.ConfiguracionVerificacionVida", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactoConfianza");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Herencia.Data.Models.ActivoDigital", b =>
                {
                    b.Navigation("AsignacionesHerencia");
                });

            modelBuilder.Entity("Herencia.Data.Models.Usuario", b =>
                {
                    b.Navigation("ActivosOtorgados");

                    b.Navigation("HerenciasRecibidas");
                });
#pragma warning restore 612, 618
        }
    }
}
