// <auto-generated />
using System;
using Herencia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Herencia.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260710133050_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Herencia.Data.Models.ActivoDigital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ActivosDigitales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Caja de ahorro en pesos",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cuenta Banco Santander",
                            Tipo = 0,
                            UsuarioCreacion = "seed",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Cuenta corriente en dolares",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cuenta Banco Galicia",
                            Tipo = 0,
                            UsuarioCreacion = "seed",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Perfil publico con 5000 seguidores",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Instagram personal",
                            Tipo = 1,
                            UsuarioCreacion = "seed",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Perfil familiar",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Facebook personal",
                            Tipo = 1,
                            UsuarioCreacion = "seed",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Wallet Ethereum",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Billetera MetaMask",
                            Tipo = 2,
                            UsuarioCreacion = "seed",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Exchange con balance en USDT",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Billetera Binance",
                            Tipo = 2,
                            UsuarioCreacion = "seed",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Cuenta de correo con backups de fotos",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Correo Gmail principal",
                            Tipo = 3,
                            UsuarioCreacion = "seed",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Cuenta de correo del trabajo anterior",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Correo Outlook laboral",
                            Tipo = 3,
                            UsuarioCreacion = "seed",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Dominio registrado en un proveedor DNS",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Dominio web personal",
                            Tipo = 4,
                            UsuarioCreacion = "seed",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Caja de ahorro en pesos",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cuenta Banco Nacion",
                            Tipo = 0,
                            UsuarioCreacion = "seed",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 11,
                            Descripcion = "Plazo fijo renovable",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cuenta Banco BBVA",
                            Tipo = 0,
                            UsuarioCreacion = "seed",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 12,
                            Descripcion = "Perfil profesional con recomendaciones",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "LinkedIn profesional",
                            Tipo = 1,
                            UsuarioCreacion = "seed",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 13,
                            Descripcion = "Hardware wallet con Bitcoin",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Billetera Ledger",
                            Tipo = 2,
                            UsuarioCreacion = "seed",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 14,
                            Descripcion = "Cuenta de respaldo",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Correo Gmail secundario",
                            Tipo = 3,
                            UsuarioCreacion = "seed",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 15,
                            Descripcion = "Suscripcion de streaming compartida",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cuenta Netflix",
                            Tipo = 4,
                            UsuarioCreacion = "seed",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 16,
                            Descripcion = "Caja de ahorro en pesos",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cuenta Banco Macro",
                            Tipo = 0,
                            UsuarioCreacion = "seed",
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 17,
                            Descripcion = "Perfil personal",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cuenta X (Twitter)",
                            Tipo = 1,
                            UsuarioCreacion = "seed",
                            UsuarioId = 3
                        });
                });

            modelBuilder.Entity("Herencia.Data.Models.AsignacionHerencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivoDigitalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CondicionLiberacion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailInvitado")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcentajeAsignado")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivoDigitalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AsignacionesHerencia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivoDigitalId = 1,
                            CondicionLiberacion = "Certificado de defuncion + 30 dias",
                            EmailInvitado = "ana.torres@example.com",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PorcentajeAsignado = 50.00m,
                            UsuarioCreacion = "seed",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 2,
                            ActivoDigitalId = 1,
                            CondicionLiberacion = "Certificado de defuncion + 30 dias",
                            EmailInvitado = "carlos.sosa@example.com",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PorcentajeAsignado = 50.00m,
                            UsuarioCreacion = "seed",
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 3,
                            ActivoDigitalId = 10,
                            CondicionLiberacion = "Certificado de defuncion",
                            EmailInvitado = "carlos.sosa@example.com",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PorcentajeAsignado = 100.00m,
                            UsuarioCreacion = "seed",
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            ActivoDigitalId = 5,
                            CondicionLiberacion = "Certificado de defuncion",
                            EmailInvitado = "invitado.sinregistro@example.com",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PorcentajeAsignado = 100.00m,
                            UsuarioCreacion = "seed"
                        },
                        new
                        {
                            Id = 5,
                            ActivoDigitalId = 13,
                            CondicionLiberacion = "Mayoria de edad del beneficiario",
                            EmailInvitado = "maximiceli@hotmail.com.ar",
                            Estado = 2,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PorcentajeAsignado = 100.00m,
                            UsuarioCreacion = "seed",
                            UsuarioId = 1
                        });
                });

            modelBuilder.Entity("Herencia.Data.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "maximiceli@hotmail.com.ar",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Maximiliano Miceli",
                            PasswordHash = new byte[] { 104, 97, 115, 104, 68, 101, 80, 114, 117, 101, 98, 97, 83, 101, 109, 105, 108, 108, 97, 49, 50, 51, 52, 53, 54 },
                            PasswordSalt = new byte[] { 115, 97, 108, 116, 68, 101, 80, 114, 117, 101, 98, 97, 83, 101, 109, 105, 108, 108, 97, 49, 50, 51, 52, 53, 54 },
                            Rol = 1,
                            UsuarioCreacion = "seed"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ana.torres@example.com",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Ana Torres",
                            PasswordHash = new byte[] { 104, 97, 115, 104, 68, 101, 80, 114, 117, 101, 98, 97, 83, 101, 109, 105, 108, 108, 97, 49, 50, 51, 52, 53, 54 },
                            PasswordSalt = new byte[] { 115, 97, 108, 116, 68, 101, 80, 114, 117, 101, 98, 97, 83, 101, 109, 105, 108, 108, 97, 49, 50, 51, 52, 53, 54 },
                            Rol = 0,
                            UsuarioCreacion = "seed"
                        },
                        new
                        {
                            Id = 3,
                            Email = "carlos.sosa@example.com",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Carlos Sosa",
                            PasswordHash = new byte[] { 104, 97, 115, 104, 68, 101, 80, 114, 117, 101, 98, 97, 83, 101, 109, 105, 108, 108, 97, 49, 50, 51, 52, 53, 54 },
                            PasswordSalt = new byte[] { 115, 97, 108, 116, 68, 101, 80, 114, 117, 101, 98, 97, 83, 101, 109, 105, 108, 108, 97, 49, 50, 51, 52, 53, 54 },
                            Rol = 0,
                            UsuarioCreacion = "seed"
                        });
                });

            modelBuilder.Entity("Herencia.Data.Models.ActivoDigital", b =>
                {
                    b.HasOne("Herencia.Data.Models.Usuario", "Usuario")
                        .WithMany("ActivosOtorgados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Herencia.Data.Models.AsignacionHerencia", b =>
                {
                    b.HasOne("Herencia.Data.Models.ActivoDigital", "ActivoDigital")
                        .WithMany("AsignacionesHerencia")
                        .HasForeignKey("ActivoDigitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Herencia.Data.Models.Usuario", "Usuario")
                        .WithMany("HerenciasRecibidas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActivoDigital");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Herencia.Data.Models.ActivoDigital", b =>
                {
                    b.Navigation("AsignacionesHerencia");
                });

            modelBuilder.Entity("Herencia.Data.Models.Usuario", b =>
                {
                    b.Navigation("ActivosOtorgados");

                    b.Navigation("HerenciasRecibidas");
                });
#pragma warning restore 612, 618
        }
    }
}
